export const themePalettes: Record<string, { 
  bg: string, 
  text: string, 
  cardBg: string, 
  cardHover: string,
  primaryBg: string,
  hoverBg: string,
  borderAccent: string,
  bgLight: string,
  textActive: string,
  hex: string
}> = {
  neutral: { 
    bg: "bg-[#F5F2EB]", 
    text: "text-[#8C7A6B]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#8C7A6B]/50",
    primaryBg: "bg-[#8C7A6B]",
    hoverBg: "hover:bg-[#8C7A6B]/90",
    borderAccent: "border-[#8C7A6B]/20",
    bgLight: "bg-[#8C7A6B]/5",
    textActive: "text-white",
    hex: "#8C7A6B"
  },
  blue: { 
    bg: "bg-[#E0F2FE]", 
    text: "text-[#0369A1]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#0369A1]/50",
    primaryBg: "bg-[#0369A1]",
    hoverBg: "hover:bg-[#0369A1]/90",
    borderAccent: "border-[#0369A1]/20",
    bgLight: "bg-[#0369A1]/5",
    textActive: "text-white",
    hex: "#0369A1"
  },
  navy: { 
    bg: "bg-[#DBEAFE]", 
    text: "text-[#1E3A8A]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#1E3A8A]/50",
    primaryBg: "bg-[#1E3A8A]",
    hoverBg: "hover:bg-[#1E3A8A]/90",
    borderAccent: "border-[#1E3A8A]/20",
    bgLight: "bg-[#1E3A8A]/5",
    textActive: "text-white",
    hex: "#1E3A8A"
  },
  aqua: { 
    bg: "bg-[#CCFBF1]", 
    text: "text-[#0F766E]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#0F766E]/50",
    primaryBg: "bg-[#0F766E]",
    hoverBg: "hover:bg-[#0F766E]/90",
    borderAccent: "border-[#0F766E]/20",
    bgLight: "bg-[#0F766E]/5",
    textActive: "text-white",
    hex: "#0F766E"
  },
  pink: { 
    bg: "bg-[#FCE7F3]", 
    text: "text-[#BE185D]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#BE185D]/50",
    primaryBg: "bg-[#BE185D]",
    hoverBg: "hover:bg-[#BE185D]/90",
    borderAccent: "border-[#BE185D]/20",
    bgLight: "bg-[#BE185D]/5",
    textActive: "text-white",
    hex: "#BE185D"
  },
  magenta: { 
    bg: "bg-[#FBCFE8]", 
    text: "text-[#9D174D]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#9D174D]/50",
    primaryBg: "bg-[#9D174D]",
    hoverBg: "hover:bg-[#9D174D]/90",
    borderAccent: "border-[#9D174D]/20",
    bgLight: "bg-[#9D174D]/5",
    textActive: "text-white",
    hex: "#9D174D"
  },
  purple: { 
    bg: "bg-[#F3E8FF]", 
    text: "text-[#6B21A8]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#6B21A8]/50",
    primaryBg: "bg-[#6B21A8]",
    hoverBg: "hover:bg-[#6B21A8]/90",
    borderAccent: "border-[#6B21A8]/20",
    bgLight: "bg-[#6B21A8]/5",
    textActive: "text-white",
    hex: "#6B21A8"
  },
  green: { 
    bg: "bg-[#D1FAE5]", 
    text: "text-[#065F46]", 
    cardBg: "bg-white", 
    cardHover: "hover:border-[#065F46]/50",
    primaryBg: "bg-[#065F46]",
    hoverBg: "hover:bg-[#065F46]/90",
    borderAccent: "border-[#065F46]/20",
    bgLight: "bg-[#065F46]/5",
    textActive: "text-white",
    hex: "#065F46"
  },
};
